import js from '@eslint/js';

export default [
    js.configs.recommended,
    {
        files: ['src/web/**/*.js'],
        languageOptions: {
            ecmaVersion: 2020,
            sourceType: 'module',
            globals: {
                // Browser globals
                saveCloudConfig: 'readonly',
                generateCloudClaim: 'readonly',
                loadESP32Devices: 'readonly',
                loadESP32Device: 'readonly',
                showAddDeviceForm: 'readonly',
                loadESP32Config: 'readonly',
                toggleESP32Fields: 'readonly',
                saveESP32Device: 'readonly',
                saveESP32Config: 'readonly',
                activateESP32Device: 'readonly',
                deleteESP32Device: 'readonly',
                testESP32Connection: 'readonly',
                claimDeviceToAccount: 'readonly',
                toggleUserMenu: 'readonly',
                logout: 'readonly',
                switchAccount: 'readonly',
                addLog: 'readonly',
                clearLogs: 'readonly',
                downloadLogs: 'readonly',
                toggleMemoryStats: 'readonly',
                setTheme: 'readonly',
                toggleTopMenu: 'readonly',
                compareSelected: 'readonly',
                closeCompareModal: 'readonly',
                viewHistoryDetails: 'readonly',
                closeHistoryModal: 'readonly',
                exportHistory: 'readonly',
                exportHistoryCSV: 'readonly',
                exportHistoryJSON: 'readonly',
                loadHistoryList: 'readonly',
                applyHistoryFilters: 'readonly',
                clearHistory: 'readonly',
                deleteHistoryItem: 'readonly',
                toggleProcessSelection: 'readonly',
                confirmModeSwitch: 'readonly',
                startDistillation: 'readonly',
                stopProcess: 'readonly',
                pauseProcess: 'readonly',
                resumeProcess: 'readonly',
                updateHeater: 'readonly',
                updatePump: 'readonly',
                toggleValve: 'readonly',
                startMashing: 'readonly',
                startHold: 'readonly',
                addMashStep: 'readonly',
                addHoldStep: 'readonly',
                startRectification: 'readonly',
                startManual: 'readonly',
                openRectificationStartModal: 'readonly',
                confirmStartRectification: 'readonly',
                closeRectificationStartModal: 'readonly',
                updateRectificationFractionsSum: 'readonly',
                applyRectificationFeedstockDefaults: 'readonly',
                showCreateProfileModal: 'readonly',
                closeProfileModal: 'readonly',
                saveProfile: 'readonly',
                viewProfile: 'readonly',
                closeProfileViewModal: 'readonly',
                quickLoadProfile: 'readonly',
                loadProfileToSettings: 'readonly',
                deleteProfile: 'readonly',
                clearUserProfiles: 'readonly',
                exportProfile: 'readonly',
                exportAllProfiles: 'readonly',
                showImportModal: 'readonly',
                closeImportModal: 'readonly',
                doImportProfiles: 'readonly',
                loadProfilesList: 'readonly',
                renderAbvValue: 'readonly',
                openRuntimeEditModal: 'readonly',
                closeRuntimeEditModal: 'readonly',
                submitRuntimeEditModal: 'readonly',
                onRuntimeEditUnitToggle: 'readonly',
                toggleDemoMode: 'readonly',
                rebootController: 'readonly',
                saveEquipment: 'readonly',
                saveMqtt: 'readonly',
                toggleMqttFields: 'readonly',
                loadPumpInfo: 'readonly',
                loadVersionInfo: 'readonly',
                saveSecurity: 'readonly',
                toggleAuthFields: 'readonly',
                saveTelegramSettings: 'readonly',
                sendTelegramTest: 'readonly',
                toggleTelegramFields: 'readonly',
                loadTelegramSettings: 'readonly',
                saveWiFi: 'readonly',
                calculateAbvCorrection: 'readonly',
                calculateDilution: 'readonly',
                fetchCurrentTempForCalc: 'readonly',
                toggleOperatorView: 'readonly',
                window: 'readonly',
                document: 'readonly',
                Element: 'readonly',
                Event: 'readonly',
                fetch: 'readonly',
                console: 'readonly',
                localStorage: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                alert: 'readonly',
                confirm: 'readonly',
                location: 'readonly',
                navigator: 'readonly',
                caches: 'readonly',
                self: 'readonly',
                Promise: 'readonly',
                URL: 'readonly',
                Number: 'readonly',
                Math: 'readonly',
                Date: 'readonly',
                JSON: 'readonly',
                String: 'readonly',
                Boolean: 'readonly',
                Array: 'readonly',
                Object: 'readonly',
                Map: 'readonly',
                Set: 'readonly',
                Blob: 'readonly',
                FileReader: 'readonly',
                updateColumnAnimation: 'readonly',
                AbortController: 'readonly',
                Notification: 'readonly',
                WebSocket: 'readonly',
                ResizeObserver: 'readonly',
                __APP_VERSION__: 'readonly',
                // External libs (loaded via <script>)
                ApexCharts: 'readonly',
            },
        },
        rules: {
            // Ослабим для legacy кода
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
            'no-undef': 'error',
            'no-redeclare': 'error',
            'no-constant-condition': 'warn',
            'no-empty': 'warn',
            'prefer-const': 'off',  // много let → const можно делать постепенно
        },
    },
    {
        ignores: ['data/**', 'node_modules/**', 'scripts/**'],
    },
];
