; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8
framework = arduino
build_src_filter = +<*> -<old/>
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
lib_deps = 
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^3.11.0
	adafruit/Adafruit BMP280 Library@^2.6.8
	adafruit/Adafruit ADS1X15@^2.5.0
	adafruit/Adafruit GFX Library@^1.11.5
	adafruit/Adafruit SSD1306@^2.5.7
	mandulaj/PZEM-004T-v30@^1.1.2
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	https://github.com/me-no-dev/AsyncTCP.git
	bblanchon/ArduinoJson@^7.0.4
	gyverlibs/FastBot2@^1.2.6
	lovyan03/LovyanGFX@^1.1.16
	https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
	waspinator/AccelStepper@^1.64
	madhephaestus/ESP32Servo@^1.1.2
	knolleary/PubSubClient@^2.8
	links2004/WebSockets
lib_ignore = WebServer
lib_ldf_mode = chain+
build_flags = 
	-Iinclude
	-I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/WiFi/src
	-I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/WiFiClientSecure/src
	-finput-charset=UTF-8
	-fexec-charset=UTF-8
	-DCORE_DEBUG_LEVEL=3
	-DBOARD_HAS_PSRAM
	-DUSE_LITTLEFS
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DPZEM_ENABLED=1
monitor_port = COM11
monitor_speed = 115200
monitor_filters = direct, esp32_exception_decoder
monitor_rts = 0
monitor_dtr = 0
upload_port = COM11
upload_speed = 115200
board_build.filesystem = littlefs
extra_scripts = 
	pre:scripts/generate_version.py
	pre:scripts/build_web.py

[env:esp32s3_ota]
extends = env:esp32s3
upload_protocol = espota
upload_port = smart-column.local
