/**
 * Smart-Column S3 - Pump driver
 *
 * Stepper motor NEMA17 + TMC2209 driver.
 *
 * STEP pulses are generated by ESP32 LEDC hardware, not by a software
 * polling loop. This avoids audible speed waves and brief stalls caused by
 * scheduler jitter when running the pump at higher rates.
 */

#include "pump.h"

#include <freertos/semphr.h>

static float mlPerRevolution = DEFAULT_PUMP_ML_PER_REV;
static float currentSpeedMlH = 0.0f;
static float appliedSpeedMlH = 0.0f;
static float targetStepsPerSec = 0.0f;
static float appliedStepsPerSec = 0.0f;
static volatile bool running = false;
static int32_t totalSteps = 0;
static double totalStepsExact = 0.0;
static float totalVolumeMl = 0.0f;
static TaskHandle_t pumpTaskHandle = NULL;
static SemaphoreHandle_t pumpMutex = NULL;
static uint32_t pumpTaskLoopCount = 0;
static uint32_t pumpCounterUpdateCount = 0;
static uint32_t pumpCooperativeSleepCount = 0;
static uint32_t pumpFastYieldCount = 0;
static uint32_t pumpLockTimeoutCount = 0;
static uint32_t pumpLastLoopAtMs = 0;
static uint32_t pumpLastYieldAtMs = 0;
static uint32_t pumpLastMotionUpdateUs = 0;

static constexpr uint32_t kPumpCounterUpdateMs = 100;
static constexpr TickType_t kPumpIdleDelayTicks = pdMS_TO_TICKS(20);
static constexpr TickType_t kPumpRunDelayTicks = pdMS_TO_TICKS(10);
static constexpr float kPumpSpeedRampStepsPerSec2 = 8000.0f;
static constexpr uint8_t kPumpLedcResolutionBits = 8;

static bool g_pumpPwmReady = false;

static void updateTotalsFromExactSteps() {
    totalSteps = static_cast<int32_t>(totalStepsExact);
    const double revolutions =
        totalStepsExact / static_cast<double>(PUMP_STEPS_PER_REV * PUMP_MICROSTEPS);
    totalVolumeMl = static_cast<float>(revolutions * mlPerRevolution);
}

static bool lockPump(TickType_t timeoutTicks = portMAX_DELAY) {
    if (pumpMutex == NULL) {
        return false;
    }

    const bool locked = xSemaphoreTake(pumpMutex, timeoutTicks) == pdTRUE;
    if (!locked) {
        pumpLockTimeoutCount++;
    }
    return locked;
}

static void unlockPump() {
    if (pumpMutex != NULL) {
        xSemaphoreGive(pumpMutex);
    }
}

static float clampStepsPerSec(float stepsPerSec) {
    if (stepsPerSec < 0.0f) {
        return 0.0f;
    }
    if (stepsPerSec > PUMP_MAX_SPEED) {
        return PUMP_MAX_SPEED;
    }
    return stepsPerSec;
}

static float mlPerHourToStepsPerSec(float mlPerHour) {
    const float revPerHour = mlPerHour / mlPerRevolution;
    const float revPerSec = revPerHour / 3600.0f;
    return revPerSec * PUMP_STEPS_PER_REV * PUMP_MICROSTEPS;
}

static float stepsPerSecToMlPerHour(float stepsPerSec) {
    const float revPerSec = stepsPerSec / (PUMP_STEPS_PER_REV * PUMP_MICROSTEPS);
    const float revPerHour = revPerSec * 3600.0f;
    return revPerHour * mlPerRevolution;
}

static void ensurePumpPwmReady() {
    if (g_pumpPwmReady) {
        return;
    }

    pinMode(PIN_PUMP_STEP, OUTPUT);
    digitalWrite(PIN_PUMP_STEP, LOW);
    g_pumpPwmReady = ledcSetup(LEDC_CHANNEL_PUMP, 1000, kPumpLedcResolutionBits) != 0;
    if (!g_pumpPwmReady) {
        LOG_E("Pump: Failed to attach STEP pin to LEDC");
        return;
    }

    ledcAttachPin(PIN_PUMP_STEP, LEDC_CHANNEL_PUMP);
    ledcWrite(LEDC_CHANNEL_PUMP, 0);
}

static void stopPumpPulsesLocked() {
    if (!g_pumpPwmReady) {
        return;
    }

    ledcWriteTone(LEDC_CHANNEL_PUMP, 0);
    ledcWrite(LEDC_CHANNEL_PUMP, 0);
}

static void applyPumpPulsesLocked() {
    if (!g_pumpPwmReady) {
        return;
    }

    const uint32_t stepRateHz = static_cast<uint32_t>(appliedStepsPerSec + 0.5f);
    if (stepRateHz == 0) {
        stopPumpPulsesLocked();
        return;
    }

    ledcWriteTone(LEDC_CHANNEL_PUMP, stepRateHz);
}

static void syncMotionLocked(uint32_t nowUs) {
    if (pumpLastMotionUpdateUs == 0) {
        pumpLastMotionUpdateUs = nowUs;
        return;
    }

    const uint32_t deltaUs = nowUs - pumpLastMotionUpdateUs;
    pumpLastMotionUpdateUs = nowUs;

    if (deltaUs == 0 || appliedStepsPerSec <= 0.0f) {
        return;
    }

    totalStepsExact += static_cast<double>(appliedStepsPerSec) *
                       (static_cast<double>(deltaUs) / 1000000.0);
    updateTotalsFromExactSteps();
}

static void setTargetSpeedLocked(float mlPerHour) {
    const float clampedStepsPerSec = clampStepsPerSec(mlPerHourToStepsPerSec(mlPerHour));
    targetStepsPerSec = clampedStepsPerSec;
    currentSpeedMlH = stepsPerSecToMlPerHour(clampedStepsPerSec);
}

static void updateAppliedSpeedLocked(uint32_t nowUs) {
    static uint32_t lastRampUpdateUs = 0;

    if (lastRampUpdateUs == 0) {
        lastRampUpdateUs = nowUs;
    }

    const uint32_t deltaUs = nowUs - lastRampUpdateUs;
    lastRampUpdateUs = nowUs;
    const float deltaSec = static_cast<float>(deltaUs) / 1000000.0f;
    const float maxDelta = kPumpSpeedRampStepsPerSec2 * deltaSec;
    const float speedError = targetStepsPerSec - appliedStepsPerSec;

    if (maxDelta <= 0.0f || fabsf(speedError) <= maxDelta) {
        appliedStepsPerSec = targetStepsPerSec;
    } else if (speedError > 0.0f) {
        appliedStepsPerSec += maxDelta;
    } else {
        appliedStepsPerSec -= maxDelta;
    }

    appliedStepsPerSec = clampStepsPerSec(appliedStepsPerSec);
    appliedSpeedMlH = stepsPerSecToMlPerHour(appliedStepsPerSec);
    applyPumpPulsesLocked();
}

static void pumpTask(void* pvParameters) {
    uint32_t lastCounterUpdate = 0;

    while (1) {
        pumpTaskLoopCount++;
        pumpLastLoopAtMs = millis();

        if (lockPump(portMAX_DELAY)) {
            const uint32_t nowUs = micros();
            syncMotionLocked(nowUs);
            updateAppliedSpeedLocked(nowUs);

            const uint32_t nowMs = millis();
            if (nowMs - lastCounterUpdate >= kPumpCounterUpdateMs) {
                lastCounterUpdate = nowMs;
                pumpCounterUpdateCount++;
            }

            unlockPump();
        }

        pumpCooperativeSleepCount++;
        pumpLastYieldAtMs = millis();
        if (running || appliedStepsPerSec > 0.0f || targetStepsPerSec > 0.0f) {
            vTaskDelay(kPumpRunDelayTicks);
        } else {
            vTaskDelay(kPumpIdleDelayTicks);
        }
    }
}

namespace Pump {

void init() {
    LOG_I("Pump: Initializing...");

    pinMode(PIN_PUMP_EN, OUTPUT);
    pinMode(PIN_PUMP_DIR, OUTPUT);
    digitalWrite(PIN_PUMP_EN, HIGH);
    digitalWrite(PIN_PUMP_DIR, LOW);

    totalSteps = 0;
    totalStepsExact = 0.0;
    totalVolumeMl = 0.0f;
    currentSpeedMlH = 0.0f;
    appliedSpeedMlH = 0.0f;
    targetStepsPerSec = 0.0f;
    appliedStepsPerSec = 0.0f;
    running = false;
    pumpTaskLoopCount = 0;
    pumpCounterUpdateCount = 0;
    pumpCooperativeSleepCount = 0;
    pumpFastYieldCount = 0;
    pumpLockTimeoutCount = 0;
    pumpLastLoopAtMs = 0;
    pumpLastYieldAtMs = 0;
    pumpLastMotionUpdateUs = micros();

    if (pumpMutex == NULL) {
        pumpMutex = xSemaphoreCreateMutex();
    }
    if (pumpMutex == NULL) {
        LOG_E("Pump: Failed to create mutex");
        return;
    }

    ensurePumpPwmReady();
    stopPumpPulsesLocked();

    if (pumpTaskHandle == NULL) {
        xTaskCreatePinnedToCore(
            pumpTask,
            "PumpTask",
            2048,
            NULL,
            1,
            &pumpTaskHandle,
            1);
    }

    LOG_I("Pump: Init complete (microsteps=%d, ml/rev=%.2f, pwm=%s)",
          PUMP_MICROSTEPS, mlPerRevolution, g_pumpPwmReady ? "ok" : "failed");
}

void start(float mlPerHour) {
    if (mlPerHour <= 0.0f) {
        stop();
        return;
    }

    if (lockPump(portMAX_DELAY)) {
        ensurePumpPwmReady();
        digitalWrite(PIN_PUMP_DIR, LOW);
        digitalWrite(PIN_PUMP_EN, LOW);
        syncMotionLocked(micros());
        setTargetSpeedLocked(mlPerHour);
        running = true;
        unlockPump();
    }

    LOG_I("Pump: Started at %.1f ml/h target (%.1f steps/s target)",
          currentSpeedMlH, targetStepsPerSec);
}

void stop() {
    if (lockPump(portMAX_DELAY)) {
        syncMotionLocked(micros());
        running = false;
        currentSpeedMlH = 0.0f;
        appliedSpeedMlH = 0.0f;
        targetStepsPerSec = 0.0f;
        appliedStepsPerSec = 0.0f;
        stopPumpPulsesLocked();
        unlockPump();
    }

    digitalWrite(PIN_PUMP_EN, HIGH);
    LOG_I("Pump: Stopped at %d", totalSteps);
}

void setSpeed(float mlPerHour) {
    if (!running) {
        start(mlPerHour);
        return;
    }

    if (mlPerHour <= 0.0f) {
        stop();
        return;
    }

    if (lockPump(portMAX_DELAY)) {
        syncMotionLocked(micros());
        setTargetSpeedLocked(mlPerHour);
        unlockPump();
    }

    LOG_D("Pump: Speed changed to %.1f ml/h target", currentSpeedMlH);
}

float getSpeed() {
    return currentSpeedMlH;
}

bool isRunning() {
    return running;
}

float getTotalVolume() {
    if (lockPump(pdMS_TO_TICKS(5))) {
        syncMotionLocked(micros());
        const float volume = totalVolumeMl;
        unlockPump();
        return volume;
    }

    return totalVolumeMl;
}

uint32_t getTotalSteps() {
    if (lockPump(pdMS_TO_TICKS(5))) {
        syncMotionLocked(micros());
        const uint32_t steps = static_cast<uint32_t>(totalSteps);
        unlockPump();
        return steps;
    }

    return static_cast<uint32_t>(totalSteps);
}

float getMaxSpeedMlH() {
    return stepsPerSecToMlPerHour(PUMP_MAX_SPEED);
}

void resetVolume() {
    if (lockPump(portMAX_DELAY)) {
        totalSteps = 0;
        totalStepsExact = 0.0;
        totalVolumeMl = 0.0f;
        pumpLastMotionUpdateUs = micros();
        unlockPump();
    }

    LOG_I("Pump: Volume reset");
}

void setCalibration(float mlPerRev) {
    if (mlPerRev > 0.0f && mlPerRev < 10.0f) {
        if (lockPump(portMAX_DELAY)) {
            syncMotionLocked(micros());
            mlPerRevolution = mlPerRev;
            updateTotalsFromExactSteps();
            if (running || targetStepsPerSec > 0.0f) {
                currentSpeedMlH = stepsPerSecToMlPerHour(targetStepsPerSec);
                appliedSpeedMlH = stepsPerSecToMlPerHour(appliedStepsPerSec);
            }
            unlockPump();
        }

        LOG_I("Pump: Calibration set to %.3f ml/rev", mlPerRev);
    } else {
        LOG_E("Pump: Invalid calibration value %.3f", mlPerRev);
    }
}

Diagnostics getDiagnostics() {
    Diagnostics diagnostics;
    const uint32_t nowMs = millis();
    diagnostics.taskAlive =
        pumpTaskHandle != NULL && pumpLastLoopAtMs > 0 && (nowMs - pumpLastLoopAtMs) < 2000;
    diagnostics.mutexReady = pumpMutex != NULL;
    diagnostics.taskLoopCount = pumpTaskLoopCount;
    diagnostics.counterUpdateCount = pumpCounterUpdateCount;
    diagnostics.cooperativeSleepCount = pumpCooperativeSleepCount;
    diagnostics.fastYieldCount = pumpFastYieldCount;
    diagnostics.lockTimeoutCount = pumpLockTimeoutCount;
    diagnostics.lastLoopAtMs = pumpLastLoopAtMs;
    diagnostics.lastYieldAtMs = pumpLastYieldAtMs;
    diagnostics.speedMlH = currentSpeedMlH;
    diagnostics.appliedSpeedMlH = appliedSpeedMlH;
    diagnostics.totalSteps = static_cast<uint32_t>(totalSteps);
    diagnostics.totalVolumeMl = totalVolumeMl;
    return diagnostics;
}

} // namespace Pump
